// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.arm.models.resources.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Nested Proxy Resource Properties.
 */
@Fluent
public final class NestedProxyResourceProperties {
    /*
     * Provisioning State of the nested child Resource
     */
    @JsonProperty(value = "provisioningState", access = JsonProperty.Access.WRITE_ONLY)
    private ProvisioningState provisioningState;

    /*
     * Nested resource description.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * Creates an instance of NestedProxyResourceProperties class.
     */
    public NestedProxyResourceProperties() {
    }

    /**
     * Get the provisioningState property: Provisioning State of the nested child Resource.
     * 
     * @return the provisioningState value.
     */
    public ProvisioningState provisioningState() {
        return this.provisioningState;
    }

    /**
     * Get the description property: Nested resource description.
     * 
     * @return the description value.
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description property: Nested resource description.
     * 
     * @param description the description value to set.
     * @return the NestedProxyResourceProperties object itself.
     */
    public NestedProxyResourceProperties withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
