// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.arm.models.resources.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The type used for update operations of the NestedProxyResource.
 */
@Fluent
public final class NestedProxyResourceUpdate {
    /*
     * The properties property.
     */
    @JsonProperty(value = "properties")
    private NestedProxyResourceUpdateProperties properties;

    /**
     * Creates an instance of NestedProxyResourceUpdate class.
     */
    public NestedProxyResourceUpdate() {
    }

    /**
     * Get the properties property: The properties property.
     * 
     * @return the properties value.
     */
    public NestedProxyResourceUpdateProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties property: The properties property.
     * 
     * @param properties the properties value to set.
     * @return the NestedProxyResourceUpdate object itself.
     */
    public NestedProxyResourceUpdate withProperties(NestedProxyResourceUpdateProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (properties() != null) {
            properties().validate();
        }
    }
}
