// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.arm.models.resources.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The updatable properties of the NestedProxyResource.
 */
@Fluent
public final class NestedProxyResourceUpdateProperties {
    /*
     * Nested resource description.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * Creates an instance of NestedProxyResourceUpdateProperties class.
     */
    public NestedProxyResourceUpdateProperties() {
    }

    /**
     * Get the description property: Nested resource description.
     * 
     * @return the description value.
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description property: Nested resource description.
     * 
     * @param description the description value to set.
     * @return the NestedProxyResourceUpdateProperties object itself.
     */
    public NestedProxyResourceUpdateProperties withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
