// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.inheritance.fluent;

import com.azure.core.http.HttpPipeline;
import java.time.Duration;

/**
 * The interface for InheritanceClient class.
 */
public interface InheritanceClient {
    /**
     * Gets Server parameter.
     * 
     * @return the endpoint value.
     */
    String getEndpoint();

    /**
     * Gets The HTTP pipeline to send requests through.
     * 
     * @return the httpPipeline value.
     */
    HttpPipeline getHttpPipeline();

    /**
     * Gets The default poll interval for long-running operation.
     * 
     * @return the defaultPollInterval value.
     */
    Duration getDefaultPollInterval();

    /**
     * Gets the FishesClient object to access its operations.
     * 
     * @return the FishesClient object.
     */
    FishesClient getFishes();
}
