// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the service clients for ResourceManagementClient.
 * Arm Resource Provider management API.
 */
package com.azure.resourcemanager.resource.fluent;
