// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.armresourceprovider2.implementation;

import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.cadl.armresourceprovider2.fluent.models.TopLevelArmResourceInner;
import com.cadl.armresourceprovider2.models.TopLevelArmResource;
import com.cadl.armresourceprovider2.models.TopLevelArmResourceProperties;
import com.cadl.armresourceprovider2.models.TopLevelArmResourceUpdate;

public final class TopLevelArmResourceImpl
    implements TopLevelArmResource, TopLevelArmResource.Definition, TopLevelArmResource.Update {
    private TopLevelArmResourceInner innerObject;

    private final com.cadl.armresourceprovider2.ArmResourceProvider2Manager serviceManager;

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public TopLevelArmResourceProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public String resourceGroupName() {
        return resourceGroupName;
    }

    public TopLevelArmResourceInner innerModel() {
        return this.innerObject;
    }

    private com.cadl.armresourceprovider2.ArmResourceProvider2Manager manager() {
        return this.serviceManager;
    }

    private String resourceGroupName;

    private String topLevelArmResourceName;

    private TopLevelArmResourceUpdate updateProperties;

    public TopLevelArmResourceImpl withExistingResourceGroup(String resourceGroupName) {
        this.resourceGroupName = resourceGroupName;
        return this;
    }

    public TopLevelArmResource create() {
        this.innerObject = serviceManager.serviceClient()
            .getTopLevelArmResourceInterfaces()
            .createOrReplaceWithResponse(resourceGroupName, topLevelArmResourceName, this.innerModel(), Context.NONE)
            .getValue();
        return this;
    }

    public TopLevelArmResource create(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getTopLevelArmResourceInterfaces()
            .createOrReplaceWithResponse(resourceGroupName, topLevelArmResourceName, this.innerModel(), context)
            .getValue();
        return this;
    }

    TopLevelArmResourceImpl(String name, com.cadl.armresourceprovider2.ArmResourceProvider2Manager serviceManager) {
        this.innerObject = new TopLevelArmResourceInner();
        this.serviceManager = serviceManager;
        this.topLevelArmResourceName = name;
    }

    public TopLevelArmResourceImpl update() {
        this.updateProperties = new TopLevelArmResourceUpdate();
        return this;
    }

    public TopLevelArmResource apply() {
        this.innerObject = serviceManager.serviceClient()
            .getTopLevelArmResourceInterfaces()
            .updateWithResponse(resourceGroupName, topLevelArmResourceName, updateProperties, Context.NONE)
            .getValue();
        return this;
    }

    public TopLevelArmResource apply(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getTopLevelArmResourceInterfaces()
            .updateWithResponse(resourceGroupName, topLevelArmResourceName, updateProperties, context)
            .getValue();
        return this;
    }

    TopLevelArmResourceImpl(TopLevelArmResourceInner innerObject,
        com.cadl.armresourceprovider2.ArmResourceProvider2Manager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
        this.resourceGroupName = ResourceManagerUtils.getValueFromIdByName(innerObject.id(), "resourceGroups");
        this.topLevelArmResourceName
            = ResourceManagerUtils.getValueFromIdByName(innerObject.id(), "topLevelArmResources");
    }

    public TopLevelArmResource refresh() {
        this.innerObject = serviceManager.serviceClient()
            .getTopLevelArmResourceInterfaces()
            .getByResourceGroupWithResponse(resourceGroupName, topLevelArmResourceName, Context.NONE)
            .getValue();
        return this;
    }

    public TopLevelArmResource refresh(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getTopLevelArmResourceInterfaces()
            .getByResourceGroupWithResponse(resourceGroupName, topLevelArmResourceName, context)
            .getValue();
        return this;
    }

    public TopLevelArmResourceImpl withProperties(TopLevelArmResourceProperties properties) {
        this.innerModel().withProperties(properties);
        return this;
    }
}
