// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.inheritance.implementation;

import com.cadl.inheritance.fluent.models.FishInner;
import com.cadl.inheritance.models.Fish;
import com.cadl.inheritance.models.FishKind;

public final class FishImpl implements Fish {
    private FishInner innerObject;

    private final com.cadl.inheritance.InheritanceManager serviceManager;

    FishImpl(FishInner innerObject, com.cadl.inheritance.InheritanceManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public FishKind kind() {
        return this.innerModel().kind();
    }

    public int age() {
        return this.innerModel().age();
    }

    public String dna() {
        return this.innerModel().dna();
    }

    public FishInner innerModel() {
        return this.innerObject;
    }

    private com.cadl.inheritance.InheritanceManager manager() {
        return this.serviceManager;
    }
}
