// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.arm.models.resources.implementation;

import com.arm.models.resources.fluent.NestedChildResourcesClient;
import com.arm.models.resources.fluent.models.NestedChildResourceInner;
import com.arm.models.resources.models.NestedChildResource;
import com.arm.models.resources.models.NestedChildResources;
import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.SimpleResponse;
import com.azure.core.util.Context;
import com.azure.core.util.logging.ClientLogger;

public final class NestedChildResourcesImpl implements NestedChildResources {
    private static final ClientLogger LOGGER = new ClientLogger(NestedChildResourcesImpl.class);

    private final NestedChildResourcesClient innerClient;

    private final com.arm.models.resources.ResourcesManager serviceManager;

    public NestedChildResourcesImpl(NestedChildResourcesClient innerClient,
        com.arm.models.resources.ResourcesManager serviceManager) {
        this.innerClient = innerClient;
        this.serviceManager = serviceManager;
    }

    public Response<NestedChildResource> getWithResponse(String resourceGroupName, String topLevelArmResourceName,
        String childResourceName, Context context) {
        Response<NestedChildResourceInner> inner = this.serviceClient()
            .getWithResponse(resourceGroupName, topLevelArmResourceName, childResourceName, context);
        if (inner != null) {
            return new SimpleResponse<>(inner.getRequest(), inner.getStatusCode(), inner.getHeaders(),
                new NestedChildResourceImpl(inner.getValue(), this.manager()));
        } else {
            return null;
        }
    }

    public NestedChildResource get(String resourceGroupName, String topLevelArmResourceName, String childResourceName) {
        NestedChildResourceInner inner
            = this.serviceClient().get(resourceGroupName, topLevelArmResourceName, childResourceName);
        if (inner != null) {
            return new NestedChildResourceImpl(inner, this.manager());
        } else {
            return null;
        }
    }

    public void delete(String resourceGroupName, String topLevelArmResourceName, String childResourceName) {
        this.serviceClient().delete(resourceGroupName, topLevelArmResourceName, childResourceName);
    }

    public void delete(String resourceGroupName, String topLevelArmResourceName, String childResourceName,
        Context context) {
        this.serviceClient().delete(resourceGroupName, topLevelArmResourceName, childResourceName, context);
    }

    public PagedIterable<NestedChildResource> listByTopLevelArmResource(String resourceGroupName,
        String topLevelArmResourceName) {
        PagedIterable<NestedChildResourceInner> inner
            = this.serviceClient().listByTopLevelArmResource(resourceGroupName, topLevelArmResourceName);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new NestedChildResourceImpl(inner1, this.manager()));
    }

    public PagedIterable<NestedChildResource> listByTopLevelArmResource(String resourceGroupName,
        String topLevelArmResourceName, Context context) {
        PagedIterable<NestedChildResourceInner> inner
            = this.serviceClient().listByTopLevelArmResource(resourceGroupName, topLevelArmResourceName, context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new NestedChildResourceImpl(inner1, this.manager()));
    }

    public PagedIterable<NestedChildResource> listBySubscription(String topLevelArmResourceName) {
        PagedIterable<NestedChildResourceInner> inner
            = this.serviceClient().listBySubscription(topLevelArmResourceName);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new NestedChildResourceImpl(inner1, this.manager()));
    }

    public PagedIterable<NestedChildResource> listBySubscription(String topLevelArmResourceName, Context context) {
        PagedIterable<NestedChildResourceInner> inner
            = this.serviceClient().listBySubscription(topLevelArmResourceName, context);
        return ResourceManagerUtils.mapPage(inner, inner1 -> new NestedChildResourceImpl(inner1, this.manager()));
    }

    public NestedChildResource getById(String id) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String topLevelArmResourceName = ResourceManagerUtils.getValueFromIdByName(id, "topLevelArmResources");
        if (topLevelArmResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'topLevelArmResources'.", id)));
        }
        String childResourceName = ResourceManagerUtils.getValueFromIdByName(id, "childResources");
        if (childResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'childResources'.", id)));
        }
        return this.getWithResponse(resourceGroupName, topLevelArmResourceName, childResourceName, Context.NONE)
            .getValue();
    }

    public Response<NestedChildResource> getByIdWithResponse(String id, Context context) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String topLevelArmResourceName = ResourceManagerUtils.getValueFromIdByName(id, "topLevelArmResources");
        if (topLevelArmResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'topLevelArmResources'.", id)));
        }
        String childResourceName = ResourceManagerUtils.getValueFromIdByName(id, "childResources");
        if (childResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'childResources'.", id)));
        }
        return this.getWithResponse(resourceGroupName, topLevelArmResourceName, childResourceName, context);
    }

    public void deleteById(String id) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String topLevelArmResourceName = ResourceManagerUtils.getValueFromIdByName(id, "topLevelArmResources");
        if (topLevelArmResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'topLevelArmResources'.", id)));
        }
        String childResourceName = ResourceManagerUtils.getValueFromIdByName(id, "childResources");
        if (childResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'childResources'.", id)));
        }
        this.delete(resourceGroupName, topLevelArmResourceName, childResourceName, Context.NONE);
    }

    public void deleteByIdWithResponse(String id, Context context) {
        String resourceGroupName = ResourceManagerUtils.getValueFromIdByName(id, "resourceGroups");
        if (resourceGroupName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'resourceGroups'.", id)));
        }
        String topLevelArmResourceName = ResourceManagerUtils.getValueFromIdByName(id, "topLevelArmResources");
        if (topLevelArmResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'topLevelArmResources'.", id)));
        }
        String childResourceName = ResourceManagerUtils.getValueFromIdByName(id, "childResources");
        if (childResourceName == null) {
            throw LOGGER.logExceptionAsError(new IllegalArgumentException(
                String.format("The resource ID '%s' is not valid. Missing path segment 'childResources'.", id)));
        }
        this.delete(resourceGroupName, topLevelArmResourceName, childResourceName, context);
    }

    private NestedChildResourcesClient serviceClient() {
        return this.innerClient;
    }

    private com.arm.models.resources.ResourcesManager manager() {
        return this.serviceManager;
    }

    public NestedChildResourceImpl define(String name) {
        return new NestedChildResourceImpl(name, this.manager());
    }
}
