// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.inheritance.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Defines values for FishKind.
 */
public final class FishKind extends ExpandableStringEnum<FishKind> {
    /**
     * Static value salmon for FishKind.
     */
    public static final FishKind SALMON = fromString("salmon");

    /**
     * Static value shark for FishKind.
     */
    public static final FishKind SHARK = fromString("shark");

    /**
     * Creates a new instance of FishKind value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public FishKind() {
    }

    /**
     * Creates or finds a FishKind from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding FishKind.
     */
    public static FishKind fromString(String name) {
        return fromString(name, FishKind.class);
    }

    /**
     * Gets known FishKind values.
     * 
     * @return known FishKind values.
     */
    public static Collection<FishKind> values() {
        return values(FishKind.class);
    }
}
