// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.inheritance.models;

import com.cadl.inheritance.fluent.models.FishInner;

/**
 * An immutable client-side representation of Fish.
 */
public interface Fish {
    /**
     * Gets the kind property: The kind property.
     * 
     * @return the kind value.
     */
    FishKind kind();

    /**
     * Gets the age property: The age property.
     * 
     * @return the age value.
     */
    int age();

    /**
     * Gets the dna property: The dna property.
     * 
     * @return the dna value.
     */
    String dna();

    /**
     * Gets the inner com.cadl.inheritance.fluent.models.FishInner object.
     * 
     * @return the inner object.
     */
    FishInner innerModel();
}
