// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.cadl.inheritance.models;

import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The third level model GoblinShark in polymorphic multiple levels inheritance.
 */
@Immutable
public final class GoblinShark extends Shark {
    /*
     * The kind property.
     */
    private FishKind kind = SharkType.fromString("shark");

    /*
     * The sharktype property.
     */
    private SharkType sharktype = SharkType.GOBLIN;

    /**
     * Creates an instance of GoblinShark class.
     */
    private GoblinShark() {
    }

    /**
     * Get the kind property: The kind property.
     * 
     * @return the kind value.
     */
    @Override
    public FishKind kind() {
        return this.kind;
    }

    /**
     * Get the sharktype property: The sharktype property.
     * 
     * @return the sharktype value.
     */
    @Override
    public SharkType sharktype() {
        return this.sharktype;
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("kind", this.kind == null ? null : this.kind.toString());
        jsonWriter.writeIntField("age", age());
        jsonWriter.writeStringField("dna", dna());
        jsonWriter.writeStringField("sharktype", this.sharktype == null ? null : this.sharktype.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of GoblinShark from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of GoblinShark if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the GoblinShark.
     */
    public static GoblinShark fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            GoblinShark deserializedGoblinShark = new GoblinShark();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("age".equals(fieldName)) {
                    deserializedGoblinShark.withAge(reader.getInt());
                } else if ("dna".equals(fieldName)) {
                    deserializedGoblinShark.withDna(reader.getString());
                } else if ("sharktype".equals(fieldName)) {
                    deserializedGoblinShark.sharktype = SharkType.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedGoblinShark;
        });
    }
}
