emit:
  - "@azure-tools/typespec-java"
options:
  "@azure-tools/typespec-java":
    emitter-output-dir: "{project-root}/tsp-output"
    partial-update: true
    namer: true
    generate-samples: true
    examples-directory: ./examples
    generate-tests: false
    enable-sync-stack: true
    dev-options:
      generate-code-model: true
